export const EXAMINATIONS = [
  {
    IDExamination: 1,
    Name: 'Prohlídka u stomatologa',
    Description: 'Preventivní prohlídka u zubaře napomáhá ke zdraví dásní, kazu i zubnímu kameni.',
    AgeFrom: 1,
    AgeUntil: 80,
    Gender: 'U',
  },
  {
    IDExamination: 2,
    Name: 'Prohlídka u praktického lékaře',
    Description: 'Preventivní prohlídka u svého praktického lékaře napomáhá s odhalením příznaků včas.',
    AgeFrom: 1,
    AgeUntil: 100,
    Gender: 'U',
  },
  {
    IDExamination: 3,
    Name: 'Prohlídka u gynekologa',
    Description: 'Preventivní prohlídka u gynekologa napomáhá ke spoustě věcí.',
    AgeFrom: 18,
    AgeUntil: 40,
    Gender: 'Z',
  },
  {
    IDExamination: 4,
    Name: 'Prohlídka u psychologa',
    Description: 'Šibe ti na věž, chlape!',
    AgeFrom: 15,
    AgeUntil: 45,
    Gender: 'M',
   },
   {
    IDExamination: 5,
    Name: 'Prohlídka u pedagoga',
    Description: 'To nejlepší pro vaše ratolesti.',
    AgeFrom: 0,
    AgeUntil: 18,
    Gender: 'U',
    },
];
